sudo: required
dist: xenial
language: go

go:
  - 1.x
  - master

# TODO (Karun): This works only if travis has k8s environment. Hence commenting it for now.
install: true
    - go get -v github.com/onsi/ginkgo/ginkgo
    - go get -v github.com/onsi/gomega
    - export PATH=$PATH:$HOME/gopath/bin

# TODO (Karun): This works only if travis has k8s environment. Hence commenting it for now.
# script: ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2

services:
  - docker

go_import_path: cni-genie/CNI-Genie

env:
  global:
    - REPO=quay.io/huawei-cni-genie
    - PLUGINREPO=quay.io/huawei-cni-genie/genie-plugin
    - ADMREPO=quay.io/huawei-cni-genie/genie-admission-controller
    - POLICYREPO=quay.io/huawei-cni-genie/genie-policy-controller

before_script:
  -  mkdir -p $HOME/gopath/src/github.com/cni-genie/CNI-Genie
  -  rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/cni-genie/CNI-Genie
  -  export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cni-genie/CNI-Genie
  -  cd $HOME/gopath/src/github.com/cni-genie/CNI-Genie

jobs:
  include:
    #- stage: "Test Jobs"
      #script:
       # - make
    #- stage: Unit Test
     # script:
      #  - make test print=y

    - stage: E2E Tests
      before_script:
          # Download kubeadm
          - sudo apt-get update && sudo apt-get install -y apt-transport-https
          - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          - sudo apt-get update
          #- sudo apt-get install -y kubelet kubeadm kubectl
          - sudo apt-get install -y kubelet kubeadm kubectl
          - sudo apt-mark hold kubelet kubeadm kubectl
          - sudo kubeadm init --pod-network-cidr=10.244.0.0/16
          - sleep 20
          - rm -rf $HOME/.kube/
          - mkdir -p $HOME/.kube
          - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
          - sudo chown $(id -u):$(id -g) $HOME/.kube/config
          - kubectl taint nodes --all node-role.kubernetes.io/master-
          - kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
      script:
          - make test-e2e testKubeVersion=1.7 testKubeConfig=/etc/kubernetes/admin.conf


after_success:
  - docker --version
  - echo 'Travis commit is:\n'
  - echo $TRAVIS_COMMIT
  - echo 'Travis Build Number is:\n'
  - echo $TRAVIS_BUILD_NUMBER
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REPO
  - docker build -t cnigenie -f conf/1.8/Dockerfile .
  - docker tag cnigenie:latest $PLUGINREPO:$TAG
  - docker tag cnigenie:latest $PLUGINREPO:$TRAVIS_BUILD_NUMBER
  - docker push $PLUGINREPO
  - docker build -t genie-adm -f controllers/network-admission-controller/Dockerfile controllers/network-admission-controller
  - docker tag genie-adm:latest $ADMREPO:$TAG
  - docker tag genie-adm:latest $ADMREPO:$TRAVIS_BUILD_NUMBER
  - docker push $ADMREPO
  - docker build -t genie-policy -f controllers/network-policy-controller/Dockerfile controllers/network-policy-controller
  - docker tag genie-policy:latest $POLICYREPO:$TAG
  - docker tag genie-policy:latest $POLICYREPO:$TRAVIS_BUILD_NUMBER
  - docker push $POLICYREPO
  - docker logout $REPO
